name: flutter_html
description: A Flutter widget for rendering static HTML and CSS as Flutter widgets.
version: 3.0.0-beta1.5
homepage: https://github.com/Sub6Resources/flutter_html

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=2.2.0'

dependencies:
  # Plugin for parsing html
  html: ^0.15.3

  # Plugin for parsing css
  csslib: ^0.17.2

  # Plugin for firstWhereOrNull extension on lists
  collection: ^1.17.0

  # plugin to manage lists and counting in a variety of styles
  list_counter: ^1.0.2

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  meta: ^1.8.0
  melos: ^3.0.1